SELECT NAME
FROM STARSIN INNER JOIN MOVIESTAR ON STARNAME=NAME
WHERE MOVIETITLE='The Usual Suspects' AND GENDER='M';

SELECT STARSIN.STARNAME
FROM STARSIN INNER JOIN MOVIE ON STARSIN.MOVIETITLE=MOVIE.TITLE
WHERE MOVIEYEAR=1995 AND STUDIONAME='MGM';


SELECT DISTINCT NAME
FROM MOVIE JOIN MOVIEEXEC ON MOVIE.PRODUCERC# = MOVIEEXEC.CERT#
WHERE STUDIONAME='MGM';

SELECT TITLE
FROM MOVIE
WHERE LENGTH > (SELECT LENGTH FROM MOVIE WHERE TITLE ='Star Wars');

SELECT NAME 
FROM MOVIEEXEC
WHERE NETWORTH > (SELECT NETWORTH FROM MOVIEEXEC WHERE NAME='Stephen Spielberg');